### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by sudoajay** [sudoajay/Github-Api#1]
- [x] add Send feedback 
- [x] add navigaton drawer
- [ ] add recycle view
- [ ] add API
